### ISSUE TITLE
kioo 0.4.0 throws NPE if deftemplate filename does not exist

### ISSUE THREAD

**Issue by timgilbert** [ckirkendall/kioo#39]
I'm guessing this is actually a problem in enlive / tagsoup, but it manifests as a kioo problem. If the filename specified in `(deftemplate)` is not found, lein cljsbuild will fail with a NullPointerException.

I added a [gist with a minimal case here](https://gist.github.com/timgilbert/9c1628d92f2ee1988357), and can provide more detail if needed but this is very easy to reproduce. [The full stack trace is here](https://gist.github.com/timgilbert/acee4ea028c315bf2ef2), but the guts of it are basically:

    Caused by: java.lang.NullPointerException
    	at net.cgrand.tagsoup$parser$fn__4889.invoke(tagsoup.clj:31)
    	at net.cgrand.tagsoup$parser.invoke(tagsoup.clj:31)
    	at net.cgrand.enlive_html$eval4930$fn__4931.invoke(enlive_html.clj:88)

Possibly this is more of a kioo -> enlive -> tagsoup dependency tree issue, but in the interests of user-friendliness, it would be nice if kioo checked to make sure the filenames specified in `deftemplate` / `defsnippet` are accessible, and throw a nicer error if they are not.

**Comment by timgilbert** [comment]
Fixed in 0.4.1-SNAPSHOT - thanks!
